apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: operator-bundle-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/operator-bundle-1-0-gamma@sha256:c441ceb755d09c2527c22c5a5b8c150996d61d3feef8ee0330b6d3b61d908a6f
        name: container-image
        resources: {}
status: {}
