apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: operator-bundle-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/operator-bundle-1-0-gamma@sha256:ae4e0340793636693b11a4d524a978a43943679cf1e860103d1f5323f524ff60
        name: container-image
        resources: {}
status: {}
