apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: operator-bundle-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/operator-bundle-1-0-gamma@sha256:52d2f6afbe8f8c8432f21fe544015ad71b55be2ffe03fc1c1ab0b4c103a1dc43
        name: container-image
        resources: {}
status: {}
