apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: operator-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/operator-1-0-gamma@sha256:44461deb1413684ae08dec942311b06c8b105093294bd7ecd93eb5630c2020e6
        name: container-image
        resources: {}
status: {}
