apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: operator-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/operator-1-0-gamma@sha256:827e90c857282cbd77814de2164f19d9274054ba8f67fb0f966005260ff6860e
        name: container-image
        resources: {}
status: {}
