apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: operator-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/operator-1-0-gamma@sha256:e92bd8aad00f2e4228505385d27dac1894f44e7ec392f04fc9b5d24ba8751aae
        name: container-image
        resources: {}
status: {}
