apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: operator-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/operator-1-0-gamma@sha256:cac12225f439784a88c2629c016a1673fc4f1972d99118842616011261ddef50
        name: container-image
        resources: {}
status: {}
