apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: operator-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator-1-0-gamma
    app.kubernetes.io/part-of: operator-1-0-gamma
  name: operator-1-0-gamma
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: operator-1-0-gamma
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: operator-1-0-gamma
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/operator-1-0-gamma@sha256:4cc4eb4029b099a9689bbfa3fc9d64e3b43b19a8fd92ca84bfc210f2989b5cdd
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
