apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sigstore-operator-bundle
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/sigstore-operator-bundle@sha256:a70168696677c4c19e1bd8423edac48ed5f1a72a8f3f83852af04706cfe573d2
        name: container-image
        resources: {}
status: {}
