apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sigstore-operator-bundle
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/sigstore-operator-bundle@sha256:68aebae2f1274752554b138c4d32ae20dd7e207f2d87f162e98217e587ca65b1
        name: container-image
        resources: {}
status: {}
